### ISSUE TITLE
Image Manipulation Node Returns Gray Image when set to RGB888p/BGR888p/RGB888i/BGR888i

### ISSUE THREAD

**Issue by gt1485a** [luxonis/depthai-core#226]
# Image Manipulation Outputs Gray Image when setFrameType is RGB/BGR/888/i/p
When using the image manipulation node to process an image from the video output of a ColorCamera node the image color planes are all set to the same value creating a gray image. 

## Current Configuration
H/W OAK-1
S/W:
   depthai version = 2.10.0.0
   opencv-python version = 4.5.2.54
   python version = 3.9.6
   
## Code to Reproduce
```python
import cv2
import depthai as dai

from depthai import *

pipeline = dai.Pipeline()

cam_rgb_node = pipeline.createColorCamera()
cam_rgb_node.setBoardSocket(dai.CameraBoardSocket.RGB)
cam_rgb_node.setResolution(dai.ColorCameraProperties.SensorResolution.THE_1080_P)


manip_node = pipeline.create(dai.node.ImageManip)
manip_node.initialConfig.setFrameType(dai.ImgFrame.Type.RGB888p)
manip_node.setMaxOutputFrameSize(1920*1080*3)

xout_rgb = pipeline.createXLinkOut()
xout_rgb.setStreamName("rgb")

cam_rgb_node.video.link(manip_node.inputImage)
manip_node.out.link(xout_rgb.input)

with dai.Device(pipeline) as device:
    q_rgb = device.getOutputQueue(name="rgb",maxSize = 1, blocking = False)
    while True:
        image = q_rgb.get()
        if image is not None:
            cv2.imshow("rgb",image.getCvFrame())

        if cv2.waitKey(1) == ord('q'):
            break
```

**Comment by alex-luxonis** [comment]
Thanks for providing the reproducible code!

Currently this is expected, when feeding YUV420p or NV12 frames to ImageManip, it could only process the Luma plane, so outputting Gray. If RGB888p / BGR888p is set as output type, a 3-plane frame is generated (all planes identical), usually suitable for feeding to a NeuralNetwork node.
Only the ColorCamera `preview` could be used to get true RGB output out of ImageManip.
https://docs.luxonis.com/projects/api/en/latest/components/nodes/image_manip/#image-formats-supported

We're working on improving ImageManip supported formats and lifting this limitation. In the meantime, we could add a warning to be reported for the case described above.

**Comment by themarpe** [comment]
@gt1485a `image_manip_refactor` branch now includes improvements to ImageManip which now handle NV12 as input as well.
Along that it also supports color space conversion, so one can input other formats as well and produce NV12 output (as well as others, RGB,BGR,planar,interleaved,gray,...)

Note: due to hw restrictions and implementation detail, inputting planar formats is faster than interleaved (eg. YUV420 vs NV12, BGR planar vs BGR interleaved, etc...)
But converting to planar/interleaved doesn't make a difference.
(Above could sometimes be the reason to use `isp` instead of video output for some operations)
